[package]
name = "reflection"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "*", features = ["full"] }
tokio = { version = "*", features = ["full"] }
http-body-util = "*"
hyper-util = { version = "*", features = ["full"] }
async-channel = "2.5.0"
rand = "0.9.2"
